with open('css/style.css', 'a', encoding='utf-8') as f:
    f.write('\n/* VIGNETTE 3D BOOK DESK SCENE */\n')
    f.write('.desk-bg { background: linear-gradient(135deg, #1e1e1e 0%, #2a2a2a 100%); padding: 60px 0; position: relative; border-radius: 12px; margin-bottom: 40px; box-shadow: inset 0 10px 30px rgba(0,0,0,0.5); }\n')
    f.write('.desk-environment { width: 100%; display: flex; flex-direction: column; align-items: center; justify-content: center; perspective: 1500px; }\n')
    f.write('.book-wrapper.realistic { transform: rotateX(25deg) rotateY(-10deg) translateZ(0); transition: transform 0.6s cubic-bezier(0.2, 0.8, 0.2, 1); box-shadow: 15px 25px 40px rgba(0, 0, 0, 0.6); background: #e0d9c8; border-radius: 4px; }\n')
    f.write('.book-wrapper.realistic:hover { transform: rotateX(15deg) rotateY(-5deg) translateZ(30px); box-shadow: 20px 35px 50px rgba(0, 0, 0, 0.7); }\n')
    f.write('.book-wrapper.realistic::before { content: \"\"; position: absolute; top: 5px; left: -15px; width: 15px; height: calc(100% - 10px); background: linear-gradient(to right, #2c2520, #423830); transform-origin: right; transform: skewY(45deg); z-index: 10; border-radius: 4px 0 0 4px; box-shadow: inset -2px 0 5px rgba(0,0,0,0.4); }\n')
    f.write('.book-wrapper.realistic::after { content: \"\"; position: absolute; bottom: -15px; left: -8px; width: 100%; height: 15px; background: linear-gradient(to bottom, #d4ccb8, #bba889); transform-origin: top; transform: skewX(45deg); border-radius: 0 0 4px 4px; box-shadow: inset 0 2px 5px rgba(0,0,0,0.2); }\n')
    f.write('.page .front.rigid, .page .back.rigid { background: #111 url(\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0IiBoZWlnaHQ9IjQiPgo8cmVjdCB3aWR0aD0iNCIgaGVpZ2h0PSI0IiBmaWxsPSIjMjIyIj48L3JlY3Q+CjxwYXRoIGQ9Ik0wIDBMNCA0Wk00IDBMMCA0WiIgc3Ryb2tlPSIjMTExIiBzdHJva2Utd2lkdGg9IjEiPjwvcGF0aD4KPC9zdmc+\"); border: 3px solid #000; }\n')
    f.write('.rigid .cover-content h2 { font-size: 2.5rem; letter-spacing: 2px; text-transform: uppercase; color: var(--accent-color); text-shadow: 0 2px 4px rgba(0,0,0,0.8); position: relative; z-index: 1; text-align: center; }\n')
    f.write('.rigid .cover-glow { position: absolute; top: 0; left: -100%; width: 50%; height: 100%; background: linear-gradient(to right, rgba(255,255,255,0), rgba(255,255,255,0.1), rgba(255,255,255,0)); transform: skewX(-20deg); animation: luxuriousGlow 6s infinite; }\n')
    f.write('@keyframes luxuriousGlow { 0% { left: -100%; } 50% { left: 200%; } 100% { left: 200%; } }\n')
    f.write('.page-content { padding: 2rem; height: 100%; display: flex; flex-direction: column; justify-content: center; background-color: #faf9f5; background-image: linear-gradient(90deg, transparent 95%, rgba(0,0,0,0.03) 100%); }\n')
    f.write('.page-content h3 { margin-bottom: 1.5rem; color: var(--text-color); font-family: var(--font-secondary); text-align: center; font-size: 1.8rem; border-bottom: 1px solid var(--accent-color); padding-bottom: 10px; }\n')
    f.write('.page-content img { border-radius: 8px; box-shadow: 0 5px 15px rgba(0,0,0,0.1); max-height: 280px; object-fit: cover; margin: auto; }\n')
    f.write('.book-controls .btn { backdrop-filter: blur(5px); background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.2); color: #fff; margin: 0 10px; cursor: pointer; }\n')
    f.write('.book-controls .btn:hover { background: var(--accent-color); border-color: var(--accent-color); }\n')
    f.write('\n/* VIGNETTE PRICE LIST */\n')
    f.write('.price-desc { text-align: center; color: #fff; margin-bottom: 2rem; font-size: 1.1rem; opacity: 0.8; }\n')
    f.write('.v-price-table { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.5rem; max-width: 1100px; margin: 0 auto; }\n')
    f.write('.price-item { background: #1a1a1a; border: 1px solid #333; border-radius: 12px; padding: 2.5rem 1.5rem 1.5rem; display: flex; flex-direction: column; position: relative; transition: transform 0.3s ease, box-shadow 0.3s ease; }\n')
    f.write('.price-item:hover { transform: translateY(-5px); box-shadow: 0 10px 25px rgba(0,0,0,0.5); border-color: var(--accent-color); }\n')
    f.write('.price-item.highlight.premium-glow { background: linear-gradient(145deg, #1e1a15 0%, #2a221a 100%); border: 2px solid var(--accent-color); box-shadow: 0 8px 30px rgba(181, 136, 104, 0.2); transform: scale(1.05); z-index: 2; }\n')
    f.write('.price-item.highlight.premium-glow:hover { transform: scale(1.05) translateY(-5px); box-shadow: 0 15px 40px rgba(181, 136, 104, 0.4); }\n')
    f.write('.price-badge { position: absolute; top: -12px; left: 50%; transform: translateX(-50%); background: var(--accent-color); color: #fff; padding: 0.3rem 1rem; border-radius: 20px; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; box-shadow: 0 4px 10px rgba(0,0,0,0.3); white-space: nowrap; }\n')
    f.write('.price-header h4 { color: #fff; font-size: 1.4rem; margin-bottom: 1.5rem; text-align: center; font-family: var(--font-secondary); }\n')
    f.write('.price-body { flex-grow: 1; margin-bottom: 2rem; }\n')
    f.write('.price-body ul { list-style: none; padding: 0; }\n')
    f.write('.price-body ul li { position: relative; padding-left: 1.5rem; margin-bottom: 0.8rem; color: #ccc; font-size: 0.95rem; line-height: 1.4; }\n')
    f.write('.price-body ul li::before { content: r\"\\f00c\"; font-family: \"Font Awesome 6 Free\"; font-weight: 900; position: absolute; left: 0; top: 2px; color: var(--accent-color); font-size: 0.9rem; }\n')
    f.write('.price-footer { text-align: center; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 1.5rem; }\n')
    f.write('.price-val { font-size: 2rem; font-weight: 700; color: var(--accent-color); display: block; }\n')
    f.write('@media (max-width: 768px) { .price-item.highlight.premium-glow { transform: scale(1); } .price-item.highlight.premium-glow:hover { transform: translateY(-5px); } }\n')
